language: python
python:
  - '2.7'
install:
  - pip install -r requirements-ci.txt
services:
  - mongodb
script: python manage.py test
before_install:
  - openssl aes-256-cbc -d -a -in client_secrets.json.enc -out silo/client_secrets.json -k $SECRET_PASS
  - sleep 15
  - mongo test --eval 'db.createUser({user:"test", pwd:"test", roles:["readWrite"]});'
