version: "2"

services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      - POSTGRES_DB=tolatables
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  mongo:
    container_name: mongo
    image: mongo:3.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_DATA_DIR=/var/lib/mongodb/data/
      - MONGO_LOG_DIR=/var/lib/mongodb/dev/null
    volumes:
      - /var/lib/mongodb/data/
    ports:
      - "27017:27017"

  tables:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tables
    image: tables
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=tola.settings.dev
      - TOLA_DEBUG=True
      - TOLA_HOSTNAME=127.0.0.1,localhost
      - TOLATABLES_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - TOLATABLES_DB_NAME=tolatables
      - TOLATABLES_DB_USER=root
      - TOLATABLES_DB_PASS=root
      - TOLATABLES_DB_HOST=postgres
      - TOLATABLES_DB_PORT=5432
      - TOLATABLES_MONGODB_NAME=admin
      - TOLATABLES_MONGODB_USER=root
      - TOLATABLES_MONGODB_PASS=root
      - TOLATABLES_MONGODB_HOST=mongo
      - TOLATABLES_MONGODB_PORT=27017
      - TOLA_ACTIVITY_API_URL=
      - TOLA_ACTIVITY_API_TOKEN=