#version: '2'
#services:
  mysqldb:
    image: mysql:5.7
    env_file: ./config/mysql.env.secret
    restart: always
   # volumes_from:
   #   - mysqldata
  #mysqldata:
   # image: cirros
   # env_file: ./config/mysql.env.secret
  #  volumes:
     #  - ./mysqlrestore.sql:/home/mysqlrestore.sql
     #  - ./mongo:/home/mongo
  #     -  /var/lib/mysql
  nginx:
     image: nginx
     restart: always
     volumes:
        - .:/home/TolaTables
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
        - "80:80"
        - "443:443"
     links:
        - tola
  mongodb:
    image: mongo
    restart: always
 #   volumes_from:
#      - mysqldata
  tola:
     build: .
     command: bash -c 'python manage.py migrate && python manage.py loaddata fixtures/tolasites.json && python manage.py loaddata fixtures/sites.json && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
     volumes:
         - .:/code
     expose:
         - "8000"
     links:
         - mysqldb
         - mongodb
